### ISSUE TITLE
Getting error when using User Assigned MSI 

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-functions-powershell-worker#235]
Trying to use managed identity to access Azure resources and getting error below during profile script run.
How is it supposed to work in a first place when sandbox code runs in is not supposed to have access to 127.0.0.1 IP address in a first place? (https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#local-address-requests)

```
2019-05-25T01:32:19.320 [Error] ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Exception: An attempt was made to access a socket in a way forbidden by its access permissions
Stack:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()

```

**Comment by anirudhgarg** [comment]
We have done the work for MSI scenario to work with our Sandbox. What is the code you are running in the profile ? Did you give the right access to the MSI to the resource ? Also, confirming that you are using this in the Windows consumption plan ? It is not supported in Linux consumption.

@mattchenderson  feel free to add any comments.

**Comment by artisticcheese** [comment]
I don't run anything inside profile, PS just try to use what is already in profile and get access to MSI account. MSI account already have neccessary permissions to subscription. Issue is not accessing resources but getting access to MSI account which fails with error specified above.
Entire content of function is below

```
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."

Import-module Az.ResourceGraph
$status = [HttpStatusCode]::OK
Connect-AzAccount -Identity
$results = Search-AzGraph -Query "where type =~ 'Microsoft.Compute/virtualmachines' |  extend disk = properties.storageProfile.osDisk.managedDisk | extend datadisk = properties.storageProfile.dataDisks | project name,  disk, datadisk" 
$body = $results | convertto-JSON -Depth 50

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
        StatusCode = $status
        Body       = $body
    })

```

Complete error

```
2019-05-28T22:48:25  Welcome, you are now connected to log-streaming service.
2019-05-28T22:48:44.206 [Information] Executing 'Functions.ResourceGraphOutput' (Reason='This function was programmatically called via the host APIs.', Id=46092060-0222-4104-9197-7b10259a6015)
2019-05-28T22:48:52.652 [Error] ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Exception: An attempt was made to access a socket in a way forbidden by its access permissions
Stack:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2019-05-28T22:48:53.041 [Error] Fail to run profile.ps1. See logs for detailed errors. Profile location: D:\home\site\wwwroot\profile.ps1.
2019-05-28T22:48:53.091 [Information] INFORMATION: PowerShell HTTP trigger function processed a request.
2019-05-28T22:48:53.861 [Error] ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: An attempt was made to access a socket in a way forbidden by its access permissions
Exception: An attempt was made to access a socket in a way forbidden by its access permissions
Stack:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2019-05-28T22:48:54.130 [Error] ERROR: Run Connect-AzAccount to login.
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: ERROR: Run Connect-AzAccount to login.
Exception: Run Connect-AzAccount to login.
Stack:    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext()
   at Microsoft.Azure.Commands.ResourceGraph.Cmdlets.SearchAzureRmGraph.GetSubscriptions()
   at Microsoft.Azure.Commands.ResourceGraph.Cmdlets.SearchAzureRmGraph.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2019-05-28T22:48:54.397 [Information] Executed 'Functions.ResourceGraphOutput' (Succeeded, Id=46092060-0222-4104-9197-7b10259a6015)
```

**Comment by aws-scripting-guy** [comment]
Getting the same issue. 

This issue can be reproduced in the Azure portal:
1. Create a new 2.0 functionapp choosing powershell language
2. Choose HTTP trigger
3. Assign user assigned MSI identity to the functionapp
4. Modify run.ps1 in the console to include 'get-azcontext' in the body of the function. 

As soon as you execute the function, it will try to load profile.ps1 with default code for assuming MSI through connect-azaccount -identity and it will throw the error above. 

Consumption Plan / Elastic Premium.

**Comment by aws-scripting-guy** [comment]
I am also experiencing this issue. I did detailed analysis - in my case the root cause is the User Assigned MSI. When I switch to System Managed MSI, I am not getting the error. 

Steps to reproduce the issue:
1. Create new function app (v2.0) with powershell runtime
2. Create new vanilla Function 
2. Select new HTTP Trigger
4. Update default code: include ```get-azcontext -verbose``` in **run.ps1** or **profile.ps1**

You should see the error above in the logs.

**Comment by anirudhgarg** [comment]
Thanks @aws-scripting-guy. @artisticcheese are you using User Assigned Identity ?

**Comment by artisticcheese** [comment]
Yes, I'm using User Assigned Identity as well.

**Comment by anirudhgarg** [comment]
@mattchenderson Do we support User Assigned MSI in Azure Functions

**Comment by artisticcheese** [comment]
Is there any move on this front? My project is on hold for several month waiting for this resolution.

**Comment by mattchenderson** [comment]
I'm not as familiar with the PowerShell side of things here, but in order to request a token from a user-assigned identity, you need to pass the client ID as a query string parameter on the request.

I would expect to see something like
`Connect-AzAccount -Identity <clientID>`

**Comment by mattchenderson** [comment]
https://github.com/Azure/azure-powershell/issues/9479

**Comment by artisticcheese** [comment]
Apparently support for User Assigned Identities is GA now in Azure functions. Does it mean this issue is resolved? 

https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity

**Comment by eamonoreilly** [comment]
Yes - I validated this on the latest Az module in Azure Functions. You can see an example on https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-2.7.0#examples (Example 7).
