### ISSUE TITLE
Occasional failures on function load requests

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-powershell-worker#276]
Occasionally, the PowerShell worker receives function load requests with the same FunctionId more than once:
```
Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: Failure
Exception: An item with the same key has already been added. Key: e4cc627e-e560-4e32-b67f-acd9403dd6ea
Stack:
    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Azure.Functions.PowerShellWorker.FunctionLoader.LoadFunction(FunctionLoadRequest request) in C:\projects\azure-functions-powershell-worker\src\FunctionLoader.cs:line 45
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 198
```
As a result, subsequent function invocations fail and the user needs to restart the app to mitigate the issue.

This seems to be a recent regression: either this message duplication started happening recently, or the PowerShell worker was able to tolerate duplicates before.

**Comment by AnatoliB** [comment]
The fix is deployed.
