### ISSUE TITLE
Null Input Bindings: Need a Method to Trap or Handle them

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#282]
Given the following function.json:
```json
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "Request",
      "methods": [
        "get",
        "post"
      ],
      "route": "HttpTrigger/{row}"
    },
    {
      "type": "table",
      "direction": "in",
      "name": "TableIn",
      "partitionKey": "HttpTrigger",
      "tableName": "HttpTrigger",
      "rowKey": "{row}"
    }
  ]
}
```

Which finds a table row "test" if https://myfunction/api/HttpTrigger/test is invoked, this works fine. However, if the table row doesn't exist, there's no way to trap the error and handle it gracefully as the command processor fails to bind the parameter at the worker level, not the script level.

```
[7/16/2019 4:15:31 PM] ERROR: Cannot bind argument to parameter 'InputObject' because it is null.
[7/16/2019 4:15:31 PM] Result: ERROR: Cannot bind argument to parameter 'InputObject' because it is null.
Exception: Cannot bind argument to parameter 'InputObject' because it is null.
Stack:    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
[7/16/2019 4:15:31 PM]    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
[7/16/2019 4:15:31 PM]    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets) 
[7/16/2019 4:15:31 PM]    at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)
[7/16/2019 4:15:31 PM]    at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)
[7/16/2019 4:15:31 PM]    at System.Management.Automation.CommandProcessor.Read().
```

### Notes
Interestingly, this open happens if you actually call $TableIn in the script, it doesn't error if it is specified in Param() but never called.
I tried Get-Variable -ErrorAction Stop and tried to try/catch it to no avail, the exception happens "below" the script at the worker level.

### Potential Solutions

1. Gracefully return a null result in the event an input binding is null (may be confused with an "intentional null"
2. Catch the exception and instead set the variable to the exceptionPass the exception so it can be handled in function logic.

**Comment by JustinGrote** [comment]
### Workaround
This works, surprisingly:
```
if ($TableIn -eq $null) {"Table Row Couldn't be Found"} else {$TableIn}
```
Maybe the underlying processor already knows if it is null before it tries to bind the variable. Magic.

So I guess this can be de-emphasized, but it still doesn't solve the "intentional null" issue.

**Comment by JustinGrote** [comment]
@AnatoliB related to this, there's no way to set a default value or anything if a binding expression doesn't exist.

As an example, consider this function.json to simply get a table row based on a passed ID path
```json

{
  "bindings": [
    {
      "authLevel": "function",
      "type"     : "httpTrigger",
      "direction": "in",
      "name"     : "Request",
      "route"    : "{id}",
      "methods"  : [
        "get"
      ]
    },
    {
      "type"        : "table",
      "direction"   : "in",
      "name"        : "TableIn",
      "tableName"   : "{sys.methodname}",
      "partitionKey": "{sys.methodname}",
      "rowKey"      : "{id}"
    }
  ]
}
```

Works fine as long as an ID is specified, however if one isn't, there's no way to set a default like "nospecified", or allow it to just silently fail and not return a table row.

I would propose being able to do something like {id?} or {id?defaultvalue} that would be in line with the route expressiosn from ASP.NET to mark a parameter as optional or set a default value if it is unspecified.
