### ISSUE TITLE
Powershell Function return body with httpstatuscode::badrequest is always empty string / null

### ISSUE THREAD

**Issue by jhealy** [Azure/azure-functions-powershell-worker#469]
I’m trying to get a ‘body’ out of a powershell function when it goes 400/HttpStatusCode::BadRequest, but I can’t seem to get the body string back out.  
Works fine with HttpStatusCode::OK.
Function.json hasn’t been mucked with.

Demonstrated in this article – doesn’t seem to work for me – [https://www.wesleyhaakman.org/powershell-for-azure-functions-introduction/ ](https://www.wesleyhaakman.org/powershell-for-azure-functions-introduction/ )

Guidance appreciated.

Expected behavior, to see “testme” in body window.
Actual behavior: empty string

**RUNNING WITH BADREQUEST**

![request-bad](https://user-images.githubusercontent.com/1870117/83179067-75ab2600-a0ef-11ea-8fb1-fd6177305dcb.jpg)

```
using namespace System.Net
param($Request, $TriggerMetadata)
# $status=[System.Net.HttpStatusCode]::OK
$status=[System.Net.HttpStatusCode]::BadRequest
$body = "testme"
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = $status
    Body = $body
})
```

**RUNNING WITH HTTPSTATUS CODE OK**

![request-good](https://user-images.githubusercontent.com/1870117/83179089-7c399d80-a0ef-11ea-90c6-a5e8db05998e.jpg)

```
using namespace System.Net
param($Request, $TriggerMetadata)
# $status=[System.Net.HttpStatusCode]::OK
$status=[System.Net.HttpStatusCode]::BadRequest
$body = "testme"
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = $status
    Body = $body
})

```

Thank you...

**Comment by vartika18** [comment]
I have also experienced the same issue where 400 behaves in a weird  fashion and always returns empty strings where the expected result should return body ..Thankyou

**Comment by jhealy** [comment]
25 days with no triage.  Had customer open a support ticket instead.  Support (Ravikamar N) acknowledged as a bug.  Fix has been rolled into old portal ( https://aka.ms/canary ) and will be implemented into upcoming revisions of new portal.

**Comment by CDSFounder** [comment]
I am having the same issue with the latest PowerShell Core and Azure Functions. If I return anything but a status 200, the body object will come back as blank. Anyone else still having this issue?

**Comment by tobvil** [comment]
Still an issue

**Comment by woter1832** [comment]
This issue seems to still exist.

### Basic HttpTrigger function app (HttpTrigger1):
```
using namespace System.Net

param($Request, $TriggerMetadata)

Write-Output "PowerShell HTTP trigger function processed a request."

$name = $Request.Query.Name

if (-not $name) {
    $requestBody = Get-Content -Raw -InputObject $Request.Body
    $data = ConvertFrom-Json $requestBody
    $name = $data.name
}

if ($name) {
    $body = @{ message = "Hello, $name" } | ConvertTo-Json
    Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
        StatusCode = [HttpStatusCode]::OK
        Body = $body
    })
}
else {
    Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
        StatusCode = [HttpStatusCode]::BadRequest
        Body = "Please pass a name on the query string or in the request body"
    })
}
```

### Response


`URL = "https://<function_app_name>.azurewebsites.net/api/HttpTrigger1?nameX=Azure"`

Note the 'X' in the `name` parameter. A deliberate mistake to cause an error.
No sign of the `body` in the exception:

```
PS C:\> $_.Exception | Select * 

Response         : StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:  
                   {
                     Date: Thu, 06 Feb 2025 22:01:42 GMT
                     Server: Kestrel
                     Transfer-Encoding: chunked
                     x-ms-middleware-request-id: 00000000-0000-0000-0000-000000000000
                     Content-Type: text/plain; charset=utf-8
                   }
HttpRequestError : Unknown
StatusCode       : BadRequest
TargetSite       : Void ThrowTerminatingError(System.Management.Automation.ErrorRecord)
Message          : Response status code does not indicate success: 400 (Bad Request).
Data             : {}
InnerException   :
HelpLink         :
Source           : System.Management.Automation
HResult          : -2146233088
StackTrace       :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

**Comment by woter1832** [comment]
Ah. Found it!

It's not in `$_.Exception` object, but in `$_`. It's actually in `$_.ErrorDetails.Message`:

```
$_ | Select *

PSMessageDetails      : 
Exception             : Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Method: GET, RequestUri: 'https://<function_app_name>.azurewebsites.net/api/HttpTrigger1?named=Azure', Version: 1.1, Content: <null>, Headers:
                        {
                          User-Agent: Mozilla/5.0
                          User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.22631; en-GB)
                          User-Agent: PowerShell/7.4.6
                          Accept-Encoding: gzip
                          Accept-Encoding: deflate
                          Accept-Encoding: br
                        }
CategoryInfo          : InvalidOperation: (Method: GET, Reques…ept-Encoding: br
                        }:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : Please pass a name on the query string or in the request body
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Users\<blah>\test-api.ps1: line 5
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```
