### ISSUE TITLE
Installing PowerShell module dependencies via requirements.psd1 doesn't work

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-functions-powershell-worker#515]
#### Summary

I am trying to create a Microsoft Azure Functions project that utilizes a third party module dependency from the PowerShell gallery. According to the documentation for Azure Functions, I should be able to simply add the dependency into the `requirements.psd1` file, and the Azure Functions runtime will automatically pull that module into my project. However, this functionality is not working as expected.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell

> Functions lets you leverage PowerShell gallery for managing dependencies. With dependency management enabled, the requirements.psd1 file is used to automatically download required modules.

#### Investigative information

I'm testing this locally for now, but also experienced the problem on Azure Functions. The same behavior occurs both locally and in the Azure Functions service.

#### Repro steps

1. Create an Azure Function App running PowerShell on Windows
2. Add a PowerShell module dependency to `requirements.psd1`
3. Add some code to `run.ps1` to call a command in the module dependency
4. Observe error message indicating that the command is not available

##### host.json

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "managedDependency": {
    "enabled": true
  }
}

```

#####

#### Expected behavior

The command exported by the PowerShell module dependency should be invoked successfully.

#### Actual behavior

The Azure Functions runtime throws an error indicating that the PowerShell command was not found.

```
[8/6/2020 9:10:39 PM] Job host started
Hosting environment: Production
Content root path: C:\Users\TrevorSullivan\git\azure-functions
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[8/6/2020 9:10:44 PM] Host lock lease acquired by instance ID '000000000000000000000000545DB49E'.
[8/6/2020 9:10:51 PM] Executing HTTP request: {
[8/6/2020 9:10:51 PM]   "requestId": "e52b0156-ae2f-4e7b-918f-30baf35c11f8",
[8/6/2020 9:10:51 PM]   "method": "GET",
[8/6/2020 9:10:51 PM]   "uri": "/api/GetNewName"
[8/6/2020 9:10:51 PM] }
[8/6/2020 9:10:51 PM] Executing 'Functions.GetNewName' (Reason='This function was programmatically called via the host APIs.', Id=05e39cfa-4c8c-4aef-8cb8-e76cd5df3788)
[8/6/2020 9:10:51 PM] System Log: { Invocation-Id: 05e39cfa-4c8c-4aef-8cb8-e76cd5df3788; Log-Level: Trace; Log-Message: Profile invocation completed in 127 ms. }
[8/6/2020 9:10:51 PM] System Log: { Invocation-Id: 05e39cfa-4c8c-4aef-8cb8-e76cd5df3788; Log-Level: Trace; Log-Message: Invoking function 'GetNewName' code 188 ms after receiving request. Invocation performance details: DependenciesAvailable: 0 ms; RunspaceAvailable: 152 ms; MetadataAndTraceContextReady: 186 ms; FunctionCodeReady: 187 ms; InputBindingValuesReady: 188 ms; InvokingFunctionCode: 188 ms;  }
[8/6/2020 9:10:51 PM] INFORMATION: PowerShell HTTP trigger function processed a request.
[8/6/2020 9:10:51 PM] System Log: { Invocation-Id: 05e39cfa-4c8c-4aef-8cb8-e76cd5df3788; Log-Level: Warning; Log-Message: CommandNotFoundException detected (error). }
[8/6/2020 9:10:51 PM] ERROR: Invoke-Generate : The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM] At C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1:27 char:12
[8/6/2020 9:10:51 PM] +     Body = Invoke-Generate -Template person
[8/6/2020 9:10:51 PM] +            ~~~~~~~~~~~~~~~
[8/6/2020 9:10:51 PM] + CategoryInfo          : ObjectNotFound: (Invoke-Generate:String) [], CommandNotFoundException
[8/6/2020 9:10:51 PM] + FullyQualifiedErrorId : CommandNotFoundException
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] Script stack trace:
[8/6/2020 9:10:51 PM]    at <ScriptBlock>, C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1: line 27
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] System.Management.Automation.CommandNotFoundException: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] Result: ERROR: Invoke-Generate : The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM] At C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1:27 char:12
[8/6/2020 9:10:51 PM] +     Body = Invoke-Generate -Template person
[8/6/2020 9:10:51 PM] +            ~~~~~~~~~~~~~~~
[8/6/2020 9:10:51 PM] + CategoryInfo          : ObjectNotFound: (Invoke-Generate:String) [], CommandNotFoundException
[8/6/2020 9:10:51 PM] + FullyQualifiedErrorId : CommandNotFoundException
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] Script stack trace:
[8/6/2020 9:10:51 PM]    at <ScriptBlock>, C:\Users\TrevorSullivan\git\azure-functions\GetNewName\run.ps1: line 27
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM] System.Management.Automation.CommandNotFoundException: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]
[8/6/2020 9:10:51 PM]
Exception: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
[8/6/2020 9:10:51 PM] Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Stack:    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[8/6/2020 9:10:51 PM]    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame).
[8/6/2020 9:10:51 PM] Executed 'Functions.GetNewName' (Succeeded, Id=05e39cfa-4c8c-4aef-8cb8-e76cd5df3788)
[8/6/2020 9:10:51 PM] Executed HTTP request: {
[8/6/2020 9:10:51 PM]   "requestId": "e52b0156-ae2f-4e7b-918f-30baf35c11f8",
[8/6/2020 9:10:51 PM]   "method": "GET",
[8/6/2020 9:10:51 PM]   "uri": "/api/GetNewName",
[8/6/2020 9:10:51 PM]   "identities": [
[8/6/2020 9:10:51 PM]     {
[8/6/2020 9:10:51 PM]       "type": "WebJobsAuthLevel",
[8/6/2020 9:10:51 PM]       "level": "Admin"
[8/6/2020 9:10:51 PM]     }
[8/6/2020 9:10:51 PM]   ],
[8/6/2020 9:10:51 PM]   "status": 204,
[8/6/2020 9:10:51 PM]   "duration": 438
[8/6/2020 9:10:51 PM] }
```

#### Known workarounds

It might be possible to manually copy the module into the function project, but that would be challenging to maintain.

#### Related information 

Provide any related information 

* Windows 10 version 2004
* Azure Functions CLI `3.0.2630`

**Comment by pcgeek86** [comment]
@AnatoliB Here you go

```
@{
    'Az' = '4.*'
    'NameIT' = '2.*'
}
```

You can also find commands on PowerShell Gallery, like this:

```powershell
Find-Command -Name invoke-generate
```

**Comment by kilasuit** [comment]
I've just been testing this out locally and it all works fine for me using this requirements.psd1

```powershell
@{
    'Az' = '4.*'
    'AzTable' = '2.0.3'
    'NameIT' ='2.1.1'
}
```
which you can see installed it
```
07/08/2020 02:44:39] System Log: { Log-Level: Information; Log-Message: PowerShell version: '7.0.0'. }
[07/08/2020 02:44:39] System Log: { Log-Level: Trace; Log-Message: First function load request completed in 623 ms. }
[07/08/2020 02:44:39] System Log: { Log-Level: Trace; Log-Message: Installing function app required modules to 'C:\Users\ryan.BLACKMARBLE\AppData\Local\AzureFunctions\PSFunctions\ManagedDependencies\200807024439552.ri' (installation mode: Required). }       
[07/08/2020 02:44:41] System Log: { Log-Level: Trace; Log-Message: Started installing module 'AzTable' version '2.0.3'. }
[07/08/2020 02:44:44] Host lock lease acquired by instance ID '0000000000000000000000003AFB4CC6'.
[07/08/2020 02:44:51] System Log: { Log-Level: Trace; Log-Message: Module name 'AzTable' version '2.0.3' has been installed. }
[07/08/2020 02:44:51] System Log: { Log-Level: Trace; Log-Message: Started installing module 'NameIT' version '2.1.1'. }
[07/08/2020 02:44:55] System Log: { Log-Level: Trace; Log-Message: Module name 'NameIT' version '2.1.1' has been installed. }
[07/08/2020 02:44:55] System Log: { Log-Level: Trace; Log-Message: Started installing module 'Az' version '4.5.0'. }
```

But because the command cache that Get-Command uses hasn't updated you will need to either `import-module NameIt` for it to work on first execution (or that's how I got it to run)

**Comment by pcgeek86** [comment]
So you're explicitly importing the module instead of relying on module auto-loading?

**Comment by AnatoliB** [comment]
Normally, Import-Module should not be required. Almost all modules are happily auto-loaded. There seems to be something special about NameIT that prevents auto-loading. This happens even in a regular brand new PS session, outside of Functions:
```
PS> Invoke-Generate
Invoke-Generate: The term 'Invoke-Generate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS> Import-Module NameIT

PS> Invoke-Generate
sklsjxug
```

**Comment by Francisco-Gamino** [comment]
Hi @pcgeek86, you do not need to import module directly; you can just rely on module autoloading.

Here are my PowerShell and Core Tools versions:
```powershell
PS C:\> func --version
3.0.2630
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

For this example, I've created a new function app with an httptrigger function. 

1) Contents of `run.ps1`:
```powershell 
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."

$cmdletList = get-command -module NameIT | % { $_.Name + [System.Environment]::NewLine }

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    Body = $cmdletList
})
```

2) Contents of `requirements.psd1`:

```powershell 
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'. 
    #'Az' = '4.*'
    'NameIT' = '2.1.1'
}
```

3) Contents of `local.settings.json`:
Notice that I've added  `"FUNCTIONS_WORKER_RUNTIME_VERSION": "~7"` so I can use `PowerShell 7` when running inside Azure Functions. 

```powershell 
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "powershell",
    "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7"
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}
```

After that, run `func start` at the function app root (where host.json is located).

From another PowerShell 7 window run:
irm http://localhost:7071/api/HttpTrigger

Your output will look like this:
![image](https://user-images.githubusercontent.com/12720858/89605185-cb9ff680-d821-11ea-9c5f-201b8199cef1.png)

Let me know if you run into any issues.

Cheers,
Francisco

**Comment by kilasuit** [comment]
Yes because the Module Analysis Cache does not have on startup of the function any details of the commands in that module due to it not having a properly defined PSD1 so it needs to be imported to actually know what commands are in it and added to the Module Analysis Cache - 

see these for more info
https://www.powershellgallery.com/packages/NameIT/2.1.1/Content/NameIT.psd1
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/AnalysisCache.cs

**Comment by AnatoliB** [comment]
@pcgeek86 The NameIT module is definitely having issues with auto-loading, as I can repro this in a regular PS session. Please either invoke `Import-Module NameIT` in your function as a workaround, or follow up with the module author if auto-loading is important to you. We can't fix this in Functions.

**Comment by kilasuit** [comment]
@Francisco-Gamino - running `Get-Command -module NameIt` will implictly load the module which is essentially the same as running `Import-Module NameIt` as shown below - hence why it works exactly the same as Import-Module like I mentioned above and shows as available in the PowerShell Session

![image](https://user-images.githubusercontent.com/6355225/89606021-e8125200-d866-11ea-90b8-80793a4deb0e.png)

@pcgeek86 - if the module had a properly formed psd1 then on install it would also properly have updated the analysis cache & is one of many reasons why `FunctionsToExport = '*'` is a frowned on bad practice - Ideally an issue should be raised on the NameIt repo to get that fixed and a proper module build task put together to compile a psm1 from all the private & public functions using perhaps ModuleBuilder - https://github.com/PoshCode/ModuleBuilder

**Comment by pcgeek86** [comment]
Calling `Import-Module` seems to have worked, but isn't it odd that module auto-loading works locally, but not in Azure? Why the inconsistency? Is module auto-loading explicitly not supported in Azure Functions? Should this get added to the docs?

The documentation currently states:

> When you start your function app, the PowerShell language worker adds this Modules folder to the $env:PSModulePath so that you can rely on module autoloading just as you would in a regular PowerShell script.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell

I understand the difference between explicitly specifying module exports vs. using `*`, which I agree is not good practice, but shouldn't this get called out somewhere more obviously?

In my modules, such as PSGitHub, I make sure to export all the commands individually in the module manifest. For example: https://github.com/pcgeek86/PSGitHub/blob/master/PSGitHub.psd1

**Comment by AnatoliB** [comment]
@pcgeek86 Module auto-loading is totally supported in Azure Functions. Other modules auto-load just fine. Like I said, NameIT (at least this specific version) has a problem with auto-loading, even in a local PS session. Make sure you create a brand new PS session and try to immediately invoke `Invoke-Generate` without invoking `Import-Module` or `Get-Command` beforehand, and you will observe the same result.
