### ISSUE TITLE
Occasional "A task was canceled" exception

### ISSUE THREAD

**Issue by VasylZvarydchuk** [Azure/azure-functions-powershell-worker#565]
I have an Azure Function in PowerShell which runs during 15-30 minutes, does a lot of work calling different external APIs and fails from time to time in different places with this exception:

```
Result: Failure
Exception: Exception calling "InvokeReturnAsIs" with "0" argument(s): "A task was canceled."
Stack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellExtensions.InvokeAndClearCommands[T](PowerShell pwsh) in D:\a\1\s\src\PowerShell\PowerShellExtensions.cs:line 45
   at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeNonOrchestrationFunction(DurableController durableController, IDictionary outputBindings) in D:\a\1\s\src\PowerShell\PowerShellManager.cs:line 283
   at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeFunction(AzFunctionInfo functionInfo, Hashtable triggerMetadata, TraceContext traceContext, IList`1 inputData, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\1\s\src\PowerShell\PowerShellManager.cs:line 226
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.InvokeFunction(AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch, InvocationRequest invocationRequest) in D:\a\1\s\src\RequestProcessor.cs:line 333
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in D:\a\1\s\src\RequestProcessor.cs:line 306
```

Here host.json

```
{
    "version": "2.0",
    "managedDependency": {
        "enabled": true
    },
    "functionTimeout": "23:59:59",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    },
    "extensions": {
        "queues": {
            "maxPollingInterval": "00:00:20",
            "visibilityTimeout": "00:05:00",
            "batchSize": 32,
            "maxDequeueCount": 1,
            "newBatchThreshold": 16
        }
    } 
}
```
AF runtime version is 3 and PowerShell 7. Mostly it fails making external long calls but very weird that it fails from time to time (1 per 15-20 successful function executions) and in different places. More over one function does about 100-150 different external web requests and only sometimes fails.

Do PowerShell Azure Functions have a special config parameter with such task timeout or is it a bug? Thanks

**Comment by AnatoliB** [comment]
@VasylZvarydchuk This is a very generic call stack that simply indicates that your Function code threw an unhandled exception. Any user code that throws an unhandled exception will lead to exactly the same call stack. The only meaningful thing the PowerShell worker is expected to do about this is to report the failure. There is no config parameter that would change that.

Since the root cause of this exception is entirely determined by the user code, I would recommend locating the command that raises the exception (you should get more data on this in the Error stream, including the line number in the Function script and the call stack in the PowerShell execution context), and either follow up with the cmdlet owners so they fix the cmdlets, or catch the exception and retry.

**Comment by VasylZvarydchuk** [comment]
Thank you @AnatoliB very much for the detailed response. Yes, apparently the issue is with `Az.Accounts` module which had a regression recently and we set it to a lower version. I'll create an issue in Az github. Closing the issue, thanks.
