### ISSUE TITLE
Importing external module introduces 'Request' parameter binding error.

### ISSUE THREAD

**Issue by adi928** [Azure/azure-functions-powershell-worker#570]
Hi there,

I have been working on a Powershell Azure function app which runs successfully locally using Visual studio Code. For loading the external module locally, I added a directory called `modules` under each function folder and included module's psm1 file in it. I did not make any change to run.ps1, and everything ran properly. But when, I am deploying the function app, I'm editing requirements.psd1 and run.ps1 (of each function) to have the external module loaded like so:

requirements.psd1
```
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    'Az' = '5.*'
    'JWT' = '1.9.0'                                   <-- For external dependency
}
```

runs.ps1
```
using namespace System.Net
Import-Module JWT                                   <-- For external dependency

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."
...
...
```

With these added, I start getting the following error locally as well as on Azure:
```
[2020-12-03T17:47:31.458Z] Worker failed to function id 8c9d8465-d674-4259-90f3-3b3cddcc1ac3.
[2020-12-03T17:47:31.458Z] Result: Failure
[2020-12-03T17:47:31.458Z] Exception: No parameter defined in the script or function for the input binding 'Request'.
[2020-12-03T17:47:31.458Z] 
[2020-12-03T17:47:31.459Z] Stack:    at Microsoft.Azure.Functions.PowerShellWorker.AzFunctionInfo..ctor(RpcFunctionMetadata metadata) in D:\a\1\s\src\FunctionInfo.cs:line 141
[2020-12-03T17:47:31.459Z]    at Microsoft.Azure.Functions.PowerShellWorker.FunctionLoader.LoadFunction(FunctionLoadRequest request) in D:\a\1\s\src\FunctionLoader.cs:line 52
[2020-12-03T17:47:31.459Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in D:\a\1\s\src\RequestProcessor.cs:line 228.
[2020-12-03T17:47:31.460Z] Worker failed to function id 7f39ed45-ab5a-44b7-92ba-69fdabdd9c7c.
[2020-12-03T17:47:31.460Z] Result: Failure
[2020-12-03T17:47:31.461Z] Exception: No parameter defined in the script or function for the input binding 'Request'.
[2020-12-03T17:47:31.461Z] 
[2020-12-03T17:47:31.461Z] Stack:    at Microsoft.Azure.Functions.PowerShellWorker.AzFunctionInfo..ctor(RpcFunctionMetadata metadata) in D:\a\1\s\src\FunctionInfo.cs:line 141
[2020-12-03T17:47:31.461Z]    at Microsoft.Azure.Functions.PowerShellWorker.FunctionLoader.LoadFunction(FunctionLoadRequest request) in D:\a\1\s\src\FunctionLoader.cs:line 52
[2020-12-03T17:47:31.528Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in D:\a\1\s\src\RequestProcessor.cs:line 228.
```

I'm fairly positive that function.json has the correct input binding, given the fact that before adding the external dependency, it was working fine locally. If it helps, here are the contents of function.json:
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "Request",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "Response"
    }
  ]
}
```

Any help with my understanding of this varied behavior with external dependency would be great. Also, if anyone has an alternative implementation of JWT which plays better with Azure functions, I'm all ears.

Some metadata for convenience:

```
Platform: Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64

func --version
3.0.2996

$host.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
2020   6      0      -1
```

Edit: I removed all mention of the external module (including the modules directory), and it is still running locally. Is there any module cache I should know about?

**Comment by AnatoliB** [comment]
@adi928 Parameters should be declared closer to the beginning of the script, otherwise PowerShell is unable to find them. Try to invoke `Import-Module` after the `param` line (or just remove `Import-Module`, it is rarely necessary).

**Comment by adi928** [comment]
Thanks @AnatoliB I don't know if it took time to reflect the various changes I applied, or something else. But the issue seem to have fixed. I'll re-open this issue if I encounter the same problem again.
