### ISSUE TITLE
Unable to run Set-Mailbox cmdlet

### ISSUE THREAD

**Issue by Jacob-Steentoft** [Azure/azure-functions-powershell-worker#689]
Hi,

I would love some help with the problem below. I've been struggling for quite a while running some simple code that keeps giving errors.

### Problem
My Durable activity fails when executing the 'Set-Mailbox' cmdlet from Exchange Management module.
I've tried to pipe input to the cmdlet and using static information instead of variables, but I still get same error.
I've also tried to run the code the Azure Function App to see if it was a problem on my local machine, but it gives the same error.

The cmdlet and code work fine outside the 'Azure Functions Core Tools'.

My guess would be that it's related to remote variables, but I do not know how to resolve the problem when using Durable.

### Orchestrator Code
```
...
if($actionItems -ne "Empty"){
    $ParallelTasks = ForEach($actionItem in $actionItems){
        Invoke-DurableActivity -FunctionName 'Activity_Set-EXORecipientLimits' -Input $actionItem -NoWait
    }
    $out = Wait-ActivityFunction -Task $ParallelTasks
} else {
    $out = "No changes applied"
}
...
```

### Activity Code
```
param($in)

Set-Mailbox -Identity $in.id -RecipientLimits $in.RecipientLimits


Write-Output "Set $($in.UserPrincipalName) to a recipient limit of $($in.RecipientLimits)"
```

### Error
```
[2021-09-30T09:05:35.968Z] EXCEPTION: Exception calling "GetSteppablePipeline" with "1" argument(s): "Cannot bind argument to parameter 'Name' because it is null."
[2021-09-30T09:05:35.971Z]
[2021-09-30T09:05:35.971Z] Exception             :
[2021-09-30T09:05:35.972Z]     Type    : System.Management.Automation.ParentContainsErrorRecordException
[2021-09-30T09:05:35.973Z]     Message : Exception calling "GetSteppablePipeline" with "1" argument(s): "Cannot bind argument to parameter 'Name' because it is null."
[2021-09-30T09:05:35.973Z]     HResult : -2146233087
[2021-09-30T09:05:35.974Z] CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
[2021-09-30T09:05:35.974Z] FullyQualifiedErrorId : CmdletInvocationException
[2021-09-30T09:05:35.975Z] InvocationInfo        :
[2021-09-30T09:05:35.976Z]     ScriptLineNumber : 69399
[2021-09-30T09:05:35.976Z]     OffsetInLine     : 13
[2021-09-30T09:05:35.977Z]     HistoryId        : -1
[2021-09-30T09:05:35.977Z]     ScriptName       : C:\Users\jacob\AppData\Local\Temp\tmp_3iajpdoo.cke\tmp_3iajpdoo.cke.psm1
[2021-09-30T09:05:35.978Z]     Line             : $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
[2021-09-30T09:05:35.979Z]
[2021-09-30T09:05:35.979Z]     PositionMessage  : At C:\Users\jacob\AppData\Local\Temp\tmp_3iajpdoo.cke\tmp_3iajpdoo.cke.psm1:69399 char:13
[2021-09-30T09:05:35.980Z]                        +             $steppablePipeline = $scriptCmd.GetSteppablePipeline($myI .
[2021-09-30T09:05:35.980Z]                        +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2021-09-30T09:05:35.981Z]     PSScriptRoot     : C:\Users\jacob\AppData\Local\Temp\tmp_3iajpdoo.cke
[2021-09-30T09:05:35.981Z]     PSCommandPath    : C:\Users\jacob\AppData\Local\Temp\tmp_3iajpdoo.cke\tmp_3iajpdoo.cke.psm1
[2021-09-30T09:05:35.982Z]     CommandOrigin    : Internal
[2021-09-30T09:05:35.983Z] ScriptStackTrace      : at <ScriptBlock><Begin>, C:\Users\jacob\AppData\Local\Temp\tmp_3iajpdoo.cke\tmp_3iajpdoo.cke.psm1: line 69399  
[2021-09-30T09:05:35.983Z]                         at <ScriptBlock>, C:\Users\jacob\Azure Functions\ExchangeAutomation\ExchangeAutomation\Activity_Set-EXORecipientLimits\run.ps1: line 3
[2021-09-30T09:05:35.984Z]
[2021-09-30T09:05:35.984Z]
[2021-09-30T09:05:35.993Z] Executed 'Functions.Activity_Set-EXORecipientLimits' (Failed, Id=e343a82e-8ce5-4962-84c6-0c2bd4fbf3ff, Duration=190ms)
[2021-09-30T09:05:35.994Z] System.Private.CoreLib: Exception while executing function: Functions.Activity_Set-EXORecipientLimits. System.Private.CoreLib: Result: Failure
Exception: Exception calling "GetSteppablePipeline" with "1" argument(s): "Cannot bind argument to parameter 'Name' because it is null."
Stack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
[2021-09-30T09:05:35.994Z]    at System.Management.Automation.Runspaces.Pipeline.Invoke()
[2021-09-30T09:05:35.995Z]    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
[2021-09-30T09:05:35.996Z]    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
[2021-09-30T09:05:35.996Z]    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
[2021-09-30T09:05:35.997Z]    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
[2021-09-30T09:05:35.998Z]    at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
[2021-09-30T09:05:35.998Z]    at System.Management.Automation.PowerShell.Invoke[T]()
[2021-09-30T09:05:35.999Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellExtensions.InvokeAndClearCommands[T](PowerShell pwsh) in /home/vsts/work/1/s/src/PowerShell/PowerShellExtensions.cs:line 45
[2021-09-30T09:05:36.000Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeNonOrchestrationFunction(DurableController durableController, IDictionary outputBindings) in /home/vsts/work/1/s/src/PowerShell/PowerShellManager.cs:line 294
[2021-09-30T09:05:36.000Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeFunction(AzFunctionInfo functionInfo, Hashtable triggerMetadata, TraceContext traceContext, IList`1 inputData, FunctionInvocationPerformanceStopwatch stopwatch) in /home/vsts/work/1/s/src/PowerShell/PowerShellManager.cs:line 229
[2021-09-30T09:05:36.001Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.InvokeFunction(AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch, InvocationRequest invocationRequest) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 333
[2021-09-30T09:05:36.002Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 306.
[2021-09-30T09:05:36.004Z] 62d35a27-fad9-48ba-bc20-41e49145e130: Function 'Activity_Set-EXORecipientLimits (Activity)' failed with an error. Reason: System.Exception:  Exception calling "GetSteppablePipeline" with "1" argument(s): "Cannot bind argument to parameter 'Name' because it is null."
[2021-09-30T09:05:36.005Z]  ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: Exception calling "GetSteppablePipeline" with "1" argument(s): "Cannot bind argument to parameter 'Name' because it is null."
Stack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
[2021-09-30T09:05:36.006Z]    at System.Management.Automation.Runspaces.Pipeline.Invoke()
[2021-09-30T09:05:36.006Z]    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
[2021-09-30T09:05:36.007Z]    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
[2021-09-30T09:05:36.008Z]    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
[2021-09-30T09:05:36.008Z]    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
[2021-09-30T09:05:36.009Z]    at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
[2021-09-30T09:05:36.009Z]    at System.Management.Automation.PowerShell.Invoke[T]()
[2021-09-30T09:05:36.010Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellExtensions.InvokeAndClearCommands[T](PowerShell pwsh) in /home/vsts/work/1/s/src/PowerShell/PowerShellExtensions.cs:line 45
[2021-09-30T09:05:36.011Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeNonOrchestrationFunction(DurableController durableController, IDictionary outputBindings) in /home/vsts/work/1/s/src/PowerShell/PowerShellManager.cs:line 294
[2021-09-30T09:05:36.011Z]    at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeFunction(AzFunctionInfo functionInfo, Hashtable triggerMetadata, TraceContext traceContext, IList`1 inputData, FunctionInvocationPerformanceStopwatch stopwatch) in /home/vsts/work/1/s/src/PowerShell/PowerShellManager.cs:line 229
[2021-09-30T09:05:36.012Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.InvokeFunction(AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch, InvocationRequest invocationRequest) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 333
[2021-09-30T09:05:36.012Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequestImpl(StreamingMessage request, AzFunctionInfo functionInfo, PowerShellManager psManager, FunctionInvocationPerformanceStopwatch stopwatch) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 306
[2021-09-30T09:05:36.013Z]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 93
[2021-09-30T09:05:36.014Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 82
[2021-09-30T09:05:36.014Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in D:\a\1\s\src\WebJobs.Script\Description\FunctionGenerator.cs:line 225
[2021-09-30T09:05:36.015Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[2021-09-30T09:05:36.015Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
[2021-09-30T09:05:36.016Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 503
[2021-09-30T09:05:36.017Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 281
[2021-09-30T09:05:36.017Z]    --- End of inner exception stack trace ---. IsReplay: False. State: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.4.1. SequenceNumber: 20. TaskEventId: 3
```

### Local development Info
- Azure Functions Core Tools
- Core Tools Version:       3.0.3734 Commit hash: 61192bb28820be76916f85209916152801483456  (64-bit)
- Function Runtime Version: 3.1.4.0
- PowerShell Version: 7

### Function Info
- Runtime Version: 3
- PowerShell Version: 7
- Platform: 32-Bit
- Managed pipeline version: Integrated
- FTP State: All allowed
- HTTP Version: 1.1
- Web sockets: Off

**Comment by stefanushinardi** [comment]
As per our testing, the module is not PowerShell Core compliant thus won't be able to run on Azure Functions PowerShell. 

Could you verify that your code run locally using PowerShell 7.0?

**Comment by Jacob-Steentoft** [comment]
> As per our testing, the module is not PowerShell Core compliant thus won't be able to run on Azure Functions PowerShell.
> 
> Could you verify that your code run locally using PowerShell 7.0?

Hi @stefanushinardi,

Running the cmdlet locally outside of Azure Functions works fine which is also how we're currently making my script work: 
```
PowerShell 7.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\jacob> Connect-ExchangeOnline
PS C:\Users\jacob> Set-Mailbox -Identity adm_jsteentoft@5ca.com -RecipientLimits 500
PS C:\Users\jacob> Set-Mailbox -Identity adm_jsteentoft@5ca.com -RecipientLimits 500
WARNING: The command completed successfully but no settings of 'adm_jsteentoft' have been modified.
```

According to the Microsoft Documentation the module should be [compliant with 7.0.3 and above](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#supported-operating-systems-for-the-exo-v2-module) if the module is version 2.0.4 or later.

My Azure Function is set to use 2.0.5 which is defined in requirements.psd1 as:
`ExchangeOnlineManagement = '2.0.5'`
and in profile.ps1 as:
```
Import-Module -Name ExchangeOnlineManagement -RequiredVersion '2.0.5'
Connect-ExchangeOnline -CertificateThumbprint $env:CertThumbprint -AppID $env:EXOAppID -Organization $env:5CATenant -ShowBanner:$false -ShowProgress $false
```
My Azure Function is also running 7.0 locally according to VS Code: 
![image](https://user-images.githubusercontent.com/7100044/141274365-03b3d728-a659-482c-825d-7c8fb8023922.png)

**Comment by Francisco-Gamino** [comment]
Hello @Jacob-Steentoft -- Could you please try installing PowerShell `7.0.7` which is the version we host in Functions and run your code locally? When you do this, do you see any errors? Thanks.
