### ISSUE TITLE
Failed to create function app dependencies destination path

### ISSUE THREAD

**Issue by jochemdevos** [Azure/azure-functions-powershell-worker#717]
Possible duplication of #327 ,which has no resolution.

No config and code changes made, invocations resulting in errors since December 1th. Last success December 5th. Contents of requirements.psd1:
`
@{
    'Az.KeyVault' = '3.*'
}`

Error message:
Result: Failure
Exception: Failed to install function app dependencies. Error: 'Failed to create function app dependencies destination path 'C:\home\data\ManagedDependencies\2112141000581664203.r'. Please make sure you have write access to this location. Error 'The user name or password is incorrect. : 'C:\home\data\ManagedDependencies\2112141000581664203.ri''. '
Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitOnDependencyInstallationTask() in /home/vsts/work/1/s/src/DependencyManagement/DependencyManager.cs:line 246
   at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitForDependenciesAvailability(Func`1 getLogger) in /home/vsts/work/1/s/src/DependencyManagement/DependencyManager.cs:line 164
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 245

**Comment by jochemdevos** [comment]
Most likely found the root cause. I was also not able to deploy the function app. A storage key was regenerated resulting in these errors:
12:31:35: Error:  Server Error in '/' Application.

 The user name or password is incorrect.

Exception Details: System.IO.IOException: The user name or password is incorrect.

Updated AzureWebJobsStorage and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING fixed the deployment issue and I suspect it will also resolve the invocation errors.
