### ISSUE TITLE
Object type meesing using MSOnline Powershell Module

### ISSUE THREAD

**Issue by khaloud40** [Azure/azure-functions-powershell-worker#738]
Hello everyone,

I'm working on Azure Functions to enable MFA per user using MSOnline Powershell module.
I was able to connect using Connect-MsolService , but an error occurred stating that this object type was missing "Microsoft.Online.Administration.StrongAuthenticationRequirement" .
I tested this on my local machine and this type is only available when we connect using Connect-MsolService.
I'm confused because I was able to run athor cmdlets for example: Get-Msoluser.
Below is my code and the error message.

Thank you in advance.
 
**Here is my Azure Functions code:**

`
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Get inputs from http Request

$password = $Request.Body.password
$username = $Request.Body.username
$userUPN =  $Request.Body.userUPN
$secureStringPwd = $password | ConvertTo-SecureString -AsPlainText -Force
$creds = New-Object System.Management.Automation.PSCredential -ArgumentList ($username,$secureStringPwd)
Import-Module MSOnline -UseWindowsPowerShell 
Connect-MsolService -Credential $creds
##############################################################################
# Prepare StrongAuthenticationRequirements object
############################################################################## 
$sa = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationRequirement
$sa.RelyingParty = "*"
$sar = @($sa)
##############################################################################
 # Enable per-user MFA for the user
##############################################################################
try
{
    Set-MsolUser -UserPrincipalName "$userUPN" -StrongAuthenticationRequirements $sar -ErrorAction Stop
    $body = "Enabled"
}
catch 
{
    $body = $_.Exception.Message
}

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    Body = $body
})
`
**Here is the error message code:**

`2022-01-14T15:34:22.127 [Error] ERROR: **Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.**Exception             :Type        : System.Management.Automation.PSArgumentExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.HResult : -2146233087CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : ArgumentMessage     : Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.ParamName   : TypeNameTargetSite  :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace  :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Source      : System.Management.AutomationHResult     : -2147024809CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExceptionFullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommandInvocationInfo        :MyCommand        : New-ObjectScriptLineNumber : 18OffsetInLine     : 7HistoryId        : 1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationRequirementPositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:18 char:7+ $sa = New-Object -TypeName Microsoft.Online.Administration.StrongAuth …+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1InvocationName   : New-ObjectCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 18Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.Exception             :Type        : System.Management.Automation.PSArgumentExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.HResult : -2146233087CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : ArgumentMessage     : Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.ParamName   : TypeNameTargetSite  :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace  :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Source      : System.Management.AutomationHResult     : -2147024809CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExceptionFullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommandInvocationInfo        :MyCommand        : New-ObjectScriptLineNumber : 18OffsetInLine     : 7HistoryId        : 1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationRequirementPositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:18 char:7+ $sa = New-Object -TypeName Microsoft.Online.Administration.StrongAuth …+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1InvocationName   : New-ObjectCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 18Exception: Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the assembly containing this type is loaded.Stack:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2022-01-14T15:34:22.628 [Error] ERROR: The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.Exception             :Type        : System.Management.Automation.RuntimeExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.HResult : -2146233087CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 19OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.RelyingParty = "*"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:19 char:1+ $sa.RelyingParty = "*"+ ~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 19TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)StackTrace  :at CallSite.Target(Closure , CallSite , Object , String )at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)Message     : The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.Data        : System.Collections.ListDictionaryInternalSource      : Anonymously Hosted DynamicMethods AssemblyHResult     : -2146233087CategoryInfo          : InvalidOperation: (:) [], RuntimeExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 19OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.RelyingParty = "*"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:19 char:1+ $sa.RelyingParty = "*"+ ~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 19Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.Exception             :Type        : System.Management.Automation.RuntimeExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.HResult : -2146233087CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 19OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.RelyingParty = "*"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:19 char:1+ $sa.RelyingParty = "*"+ ~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 19TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)StackTrace  :at CallSite.Target(Closure , CallSite , Object , String )at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)Message     : The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.Data        : System.Collections.ListDictionaryInternalSource      : Anonymously Hosted DynamicMethods AssemblyHResult     : -2146233087CategoryInfo          : InvalidOperation: (:) [], RuntimeExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 19OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.RelyingParty = "*"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:19 char:1+ $sa.RelyingParty = "*"+ ~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 19Exception: The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.Stack:    at CallSite.Target(Closure , CallSite , Object , String )at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-01-14T15:34:22.647 [Error] ERROR: The property 'State' cannot be found on this object. Verify that the property exists and can be set.Exception             :Type        : System.Management.Automation.RuntimeExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : The property 'State' cannot be found on this object. Verify that the property exists and can be set.HResult : -2146233087CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 20OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.State = "$State"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:20 char:1+ $sa.State = "$State"+ ~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 20TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)StackTrace  :at CallSite.Target(Closure , CallSite , Object , String )at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)Message     : The property 'State' cannot be found on this object. Verify that the property exists and can be set.Data        : System.Collections.ListDictionaryInternalSource      : Anonymously Hosted DynamicMethods AssemblyHResult     : -2146233087CategoryInfo          : InvalidOperation: (:) [], RuntimeExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 20OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.State = "$State"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:20 char:1+ $sa.State = "$State"+ ~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 20Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: The property 'State' cannot be found on this object. Verify that the property exists and can be set.Exception             :Type        : System.Management.Automation.RuntimeExceptionErrorRecord :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : The property 'State' cannot be found on this object. Verify that the property exists and can be set.HResult : -2146233087CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 20OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.State = "$State"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:20 char:1+ $sa.State = "$State"+ ~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 20TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)StackTrace  :at CallSite.Target(Closure , CallSite , Object , String )at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)Message     : The property 'State' cannot be found on this object. Verify that the property exists and can be set.Data        : System.Collections.ListDictionaryInternalSource      : Anonymously Hosted DynamicMethods AssemblyHResult     : -2146233087CategoryInfo          : InvalidOperation: (:) [], RuntimeExceptionFullyQualifiedErrorId : PropertyNotFoundInvocationInfo        :ScriptLineNumber : 20OffsetInLine     : 1HistoryId        : -1ScriptName       : C:\home\site\wwwroot\HttpTrigger1\run.ps1Line             : $sa.State = "$State"PositionMessage  : At C:\home\site\wwwroot\HttpTrigger1\run.ps1:20 char:1+ $sa.State = "$State"+ ~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\HttpTrigger1PSCommandPath    : C:\home\site\wwwroot\HttpTrigger1\run.ps1CommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\HttpTrigger1\run.ps1: line 20Exception: The property 'State' cannot be found on this object. Verify that the property exists and can be set.Stack:    at CallSite.Target(Closure , CallSite , Object , String )at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)`

**Comment by Francisco-Gamino** [comment]
Hello @khaloud40 -- Are you still facing this issue? if you are, could you please open a support ticket so we can take a closer look? To do so, please follow this instructions: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. Thanks.
