### ISSUE TITLE
Azure Function Parser doesn't take dependent modules into consideration

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-powershell-worker#800]
If I have a module that implements a custom enum, I cannot use that enum in my run.ps1 even if I have `#requires -module myCustomModule defined`. This is because the function info AST parser does not load these modules/types prior to parse in the runspace.

https://github.com/Azure/azure-functions-powershell-worker/blob/c77e1b705b4c8cd4bb37d508dba7bbb9c6bfbd44/src/FunctionInfo.cs#L163

```
[2022-04-20T14:56:29.713Z] Worker failed to load function: 'PushHttpOutputBindingDemo' with function id: '8f898310-1762-403a-9c7c-7fe3970da7cd'.
[2022-04-20T14:56:29.716Z] Result: Failure
Exception: The script file 'C:\Users\JGrote\Projects\AzureFunctionsMissingManual\FunctionApp\PushHttpOutputBindingDemo\run.ps1' has parsing errors:      
Attribute argument must be a constant or a script block.
[2022-04-20T14:56:29.719Z]
Stack:    at Microsoft.Azure.Functions.PowerShellWorker.AzFunctionInfo.GetParameters(String scriptFile, String entryPoint, ScriptBlockAst& scriptAst) in /home/vsts/work/1/s/src/FunctionInfo.cs:line 186
[2022-04-20T14:56:29.722Z]    at Microsoft.Azure.Functions.PowerShellWorker.AzFunctionInfo..ctor(RpcFunctionMetadata metadata) in /home/vsts/work/1/s/src/FunctionInfo.cs:line 73
[2022-04-20T14:56:29.725Z]    at Microsoft.Azure.Functions.PowerShellWorker.FunctionLoader.LoadFunction(FunctionLoadRequest request) in /home/vsts/work/1/s/src/FunctionLoader.cs:line 52
[2022-04-20T14:56:29.727Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 223.
```

**Comment by Francisco-Gamino** [comment]
Hello @JustinGrote -- Thank you for reporting this issue. Have you tried importing the module in the `profile.ps1` ?

**Comment by JustinGrote** [comment]
@Francisco-Gamino No dice, I'm pretty sure your parser isn't taking the runspace context into consideration.

Profile.ps1
```
Import-Module AzureFunctionsHelpers
```

```run.ps1
#requires -module AzureFunctionsHelpers
using namespace Microsoft.Azure.Functions.Worker

param(
    [HttpTrigger([AuthorizationLevel]::Anonymous, ('GET', 'POST'))]
    [HttpRequestContext]$Request,
    $TriggerMetadata
)

# Write to the Azure Functions log stream.
Write-Host 'PowerShell HTTP trigger function processed a request.'
```


```
[2022-04-21T00:27:40.712Z] Worker failed to load function: 'PushHttpOutputBindingDemo' with function id: '1d533830-db97-4ea6-8d87-6ba1508acd76'.
[2022-04-21T00:27:40.716Z] Result: Failure
Exception: The script file 'C:\Users\JGrote\Projects\AzureFunctionsMissingManual\FunctionApp\PushHttpOutputBindingDemo\run.ps1' has parsing errors:
Attribute argument must be a constant or a script block.
```

This works just fine locally, however in the functions host it's not recognizing the authorizationlevel enum that comes from the .dll loaded in the module because the parse statement I referenced isn't running in the relevant runspace context, so it's not aware of it.

**Comment by JustinGrote** [comment]
I should also note, as a workaround, I can use the string representation of the enum.

**Comment by Francisco-Gamino** [comment]
Hi @JustinGrote -- Great to hear that you found a workaround. We will investigate this issue and triage it accordingly.

**Comment by Francisco-Gamino** [comment]
This issue was also reported in this [CRI](https://portal.microsofticm.com/imp/v3/incidents/details/308954497/home).
