### ISSUE TITLE
Unable to install Graph.API module & PnP in Azure Functions 

### ISSUE THREAD

**Issue by potluri96** [Azure/azure-functions-powershell-worker#822]
@{
# For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
# To use the Az module in your function app, please uncomment the line below.
# 'Az' = '8.'
'Microsoft.Graph' = '1.'
'PnP.PowerShell' = '1.*'
}

2022-06-10T21:47:16.874 [Warning] The first managed dependency download is in progress, function execution will continue when it's done. Depending on the content of requirements.psd1, this can take a few minutes. Subsequent function executions will not block and updates will be performed in the background.

2022-06-10T21:47:53.575 [Error] Executed 'Functions.SPO-Consumption' (Failed, Id=a919b3a5-7f1c-49e5-8a42-966141551a94, Duration=36760ms)Result: FailureException: Failed to install function app dependencies. Error: 'Failed to install function app dependencies. Error: 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to save the module 'PnP.PowerShell'.''Stack: at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitOnDependencyInstallationTask() in /mnt/vss/_work/1/s/src/DependencyManagement/DependencyManager.cs:line 248at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitForDependenciesAvailability(Func`1 getLogger) in /mnt/vss/_work/1/s/src/DependencyManagement/DependencyManager.cs:line 165at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in /mnt/vss/_work/1/s/src/RequestProcessor.cs:line 255

2022-06-10T21:48:33.094 [Information] Executing 'Functions.SPO-Consumption' (Reason='This function was programmatically called via the host APIs.', Id=75ef4fd7-0cac-43d5-89a8-671dc1a5ed0c)
2022-06-10T21:48:33.115 [Warning] The first managed dependency download is in progress, function execution will continue when it's done. Depending on the content of requirements.psd1, this can take a few minutes. Subsequent function executions will not block and updates will be performed in the background.

2022-06-10T21:49:26.443 [Error] Executed 'Functions.SPO-Consumption' (Failed, Id=75ef4fd7-0cac-43d5-89a8-671dc1a5ed0c, Duration=53364ms)Result: FailureException: Failed to install function app dependencies. Error: 'Failed to install function app dependencies. Error: 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to save the module 'Microsoft.Graph'.''Stack: at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitOnDependencyInstallationTask() in /mnt/vss/_work/1/s/src/DependencyManagement/DependencyManager.cs:line 248at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitForDependenciesAvailability(Func`1 getLogger) in /mnt/vss/_work/1/s/src/DependencyManagement/DependencyManager.cs:line 165at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in /mnt/vss/_work/1/s/src/RequestProcessor.cs:line 255

**Comment by Francisco-Gamino** [comment]
@michaelpeng36 -- Could you please set up a repro for this on Linux? Thanks.

**Comment by michaelpeng36** [comment]
@potluri96 Setting up a PowerShell function app on Linux (Focal) with the `requirements.psd1` you specified resulted in an error, but it does not quite match the messages you're seeing. In particular, here is the error message I'm receiving
```
[2022-06-16T22:55:31.850Z] Worker failed to load function: 'foo' with function id: '09fbf797-b946-4def-94a6-76c6d61d6cee'.
[2022-06-16T22:55:31.851Z] Result: Failure
[2022-06-16T22:55:31.851Z] Exception: Failed to install function app dependencies. Error: 'Version specification '8.' is not in the correct format. Please specify the exact version or use the following notation: 'MajorVersion.*''
[2022-06-16T22:55:31.851Z] Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.Initialize(ILogger logger) in /mnt/vss/_work/1/s/src/DependencyManagement/DependencyManager.cs:line 120
[2022-06-16T22:55:31.851Z]    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.Initialize(StreamingMessage request, ILogger logger) in /mnt/vss/_work/1/s/src/DependencyManagement/DependencyManager.cs:line 92
[2022-06-16T22:55:31.851Z]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in /mnt/vss/_work/1/s/src/RequestProcessor.cs:line 198.
```
Could you try adding an asterisk after the versions specified for `Az` and `Microsoft.Graph`?

**Comment by ghost** [comment]
This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.
