### ISSUE TITLE
Powershell functions.. Connect-MsolService giving TLS error

### ISSUE THREAD

**Issue by sanalkr** [Azure/azure-functions-powershell-worker#856]
I am trying to use MSOnline in Azure Function Powershell to manage AuthenticationMethods for **Azure AD B2C Tenant**

```
using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

Import-Module MsOnline -UseWindowsPowershell

$objectId = "<object_id>"

$username = $env:supportadminuser
$passwd = ConvertTo-SecureString $env:supportpassoword -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential($username, $passwd)

[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

Connect-MsolService -Credential $cred   # Failure Here
    
Write-Host "Getting user upn"
$upn = (Get-MsolUser -ObjectId $objectId).UserPrincipalName
if($upn){
    Reset-MsolStrongAuthenticationMethodByUpn -UserPrincipalName $upn
    Write-Host "MFA reset complete"
    $body = "MFA Reset successfully."

    $status = [HttpStatusCode]::OK
}

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = $status
    Body = $body
})

```
But while running the function on Azure, I am facing the error _"You are using TLS version 1.0, 1.1 and/or 3DES cipher which are deprecated to improve the security posture of Azure AD."_
I have added the below statement but still, this error is occurring. 

I can't seem to figure out what's going wrong here.

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
```

```
2022-08-29T16:41:11Z   [Error]   ERROR: Authentication Error: Unexpected authentication failure.

OriginInfo            : localhost
Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.Exception: Authentication Error: Unexpected authentication failure. ---> 
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS1002016: 
You are using TLS version 1.0, 1.1 and/or 3DES cipher which are deprecated to improve the 
security posture of Azure AD. Your TenantID is: <tenant id>. 
Please refer to https://go.microsoft.com/fwlink/?linkid=2161187 and 
conduct needed actions to remediate the issue. For further questions, please contact your administrator.
                                     Trace ID: bf2368b2-42c3-4caf-90f7-850e36234300
                                     Correlation ID: 2bb7e95e-a55d-4a00-bce3-93f293bdddda
                                     Timestamp: 2022-08-29 16:41:10Z ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Response status code does not indicate success: 400 (BadRequest).
                                     at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Core\OAuth2\OAuthClient.cs:line 62
                                     --- End of inner exception stack trace ---
                                     at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Core\OAuth2\OAuthClient.cs:line 120
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__17`1.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Core\OAuth2\OAuthClient.cs:line 0
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__75.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 405
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__72.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 333
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__62.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 266
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__60.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 241
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\AuthenticationContext.cs:line 542
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Features\WinCommon\AuthenticationContextIntegratedAuthExtensions.cs:line 59
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                                     at Microsoft.Online.Administration.Automation.CommonFiles.AuthManager.AuthenticateUser(AuthenticationContext ac, PSCredential cred) in X:\bt\1225946\repo\src\dev\PowerShell.V1\modules\psmodule\CommonFiles\AuthManager.cs:line 115
                                     --- End of inner exception stack trace ---
                                     at Microsoft.Online.Administration.Automation.CommonFiles.AuthManager.ProcessADALException(AdalException aeGeneral, AuthenticationContext ac, IDictionary`2 accessTokens) in X:\bt\1225946\repo\src\dev\PowerShell.V1\modules\psmodule\CommonFiles\AuthManager.cs:line 537
                                     at Microsoft.Online.Administration.Automation.CommonFiles.AuthManager.AuthenticateUser(AuthenticationContext ac, PSCredential cred) in X:\bt\1225946\repo\src\dev\PowerShell.V1\modules\psmodule\CommonFiles\AuthManager.cs:line 136
                                     at Microsoft.Online.Administration.Automation.ConnectMsolService.MsolCmdletProcessRecord() in X:\bt\1225946\repo\src\dev\PowerShell.V1\modules\psmodule\Cmdlets\Connect-Service.cs:line 247
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
  
```

requirements.psd1
```
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    # To use the Az module in your function app, please uncomment the line below.
    # 'Az' = '8.*'
    'MSOnline' = '1.1.183.66'
}
```

![image](https://user-images.githubusercontent.com/20180412/187261113-8f5fdcd5-3247-44f2-b225-d75d91d35323.png)

![image](https://user-images.githubusercontent.com/20180412/187263578-5ab90543-f160-4b93-b7a5-c81a3d4fc613.png)

**Comment by AnatoliB** [comment]
Modules imported with the `-UseWindowsPowerShell` are in fact loaded to a separate Windows PowerShell session in a separate process (see [about Windows PowerShell Compatibility](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility)). Changing the `[Net.ServicePointManager]::SecurityProtocol` variable in the local process does not affect other processes. You need to update this variable in the *remote* process, here is how:

``` powershell
$session = Get-PSSession -Name WinPSCompatSession

Invoke-Command -Session $session -Command {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
}
```
