### ISSUE TITLE
Various socket/http connection exceptions in PowerShell functions

### ISSUE THREAD

**Issue by v-bafa** [Azure/azure-functions-powershell-worker#966]
Hello,

I have a function app 15 timer trigger PowerShell functions as well as 3 queue trigger functions.
These timer trigger functions are running every 5/10/15 minutes. 
The connections for the function app keeps raising till maximum limitation, then every invocation failed with connection failures. After I restarted the function app, everything works again. Are these connections supposed to close after each invocation? 

Could someone help take a look if I missed anything in the configuration? Thank you!

![image](https://github.com/Azure/azure-functions-powershell-worker/assets/28908609/4567a389-46a7-4afb-88a0-61ec65f2f695)

Exception1

> ERROR: An existing connection was forcibly closed by the remote host.
Exception             : 
    Type            : System.Net.Sockets.SocketException
    Message         : An existing connection was forcibly closed by the remote host.
    SocketErrorCode : ConnectionReset
    ErrorCode       : 10054
    NativeErrorCode : 10054
    TargetSite      : 
        Name          : GetSecret
        DeclaringType : Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient, Microsoft.Azure.PowerShell.Cmdlets.KeyVault, Version=4.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : Microsoft.Azure.PowerShell.Cmdlets.KeyVault.dll
    Source          : Microsoft.Azure.PowerShell.Cmdlets.KeyVault
    HResult         : -2147467259
    StackTrace      : 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.FlushAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName, String secretVersion)
   at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
CategoryInfo          : CloseError: (:) [Get-AzKeyVaultSecret], SocketException
FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
InvocationInfo        : 
    MyCommand        : Get-AzKeyVaultSecret
    ScriptLineNumber : 103
    OffsetInLine     : 36
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1
    Line             : $Global:SecuredPassword = (Get-AzKeyVaultsecret -VaultName $ENV:ADMIN_USER_KV -Name $ENV:ADMIN_USER_SECRET).SecretValue                       
    PositionMessage  : At C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1:103 char:36
                       + … Password = (Get-AzKeyVaultsecret -VaultName $ENV:ADMIN_USER_KV -Name  …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\Modules\Execute-RemoteScript
    PSCommandPath    : C:\home\site\wwwroot\Modules\xecute-RemoteScript\Execute-RemoteScript.psm1
    InvocationName   : Get-AzKeyVaultsecret
    CommandOrigin    : Internal
ScriptStackTrace      : at Invoke-RemoteScript, C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1: line 103
                        at <ScriptBlock>, C:\home\site\wwwroot\function1\run.ps1: line 55
PipelineIterationInfo :

Exception2:

> ERROR: A task was canceled.
Exception             : 
    Type              : System.Threading.Tasks.TaskCanceledException
    Task              : System.Threading.Tasks.Task
    CancellationToken : System.Threading.CancellationToken
    TargetSite        : 
        Name          : GetSecret
        DeclaringType : Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient, Microsoft.Azure.PowerShell.Cmdlets.KeyVault, Version=4.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : Microsoft.Azure.PowerShell.Cmdlets.KeyVault.dll
    Message           : A task was canceled.
    Source            : Microsoft.Azure.PowerShell.Cmdlets.KeyVault
    HResult           : -2146233029
    StackTrace        : 
   at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName, String secretVersion)
   at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
CategoryInfo          : CloseError: (:) [Get-AzKeyVaultSecret], TaskCanceledException
FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
InvocationInfo        : 
    MyCommand        : Get-AzKeyVaultSecret
    ScriptLineNumber : 103
    OffsetInLine     : 36
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1
    Line             : $Global:SecuredPassword = (Get-AzKeyVaultsecret -VaultName $ENV:ADMIN_USER_KV -Name $ENV:ADMIN_USER_SECRET).SecretValue                       
    PositionMessage  : At C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1:103 char:36
                       + … Password = (Get-AzKeyVaultsecret -VaultName $ENV:ADMIN_USER_KV -Name  …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\Modules\Execute-RemoteScript
    PSCommandPath    : C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1
    InvocationName   : Get-AzKeyVaultsecret
    CommandOrigin    : Internal
ScriptStackTrace      : at Invoke-RemoteScript, C:\home\site\wwwroot\Modules\Execute-RemoteScript\Execute-RemoteScript.psm1: line 103
                        at <ScriptBlock>, C:\home\site\wwwroot\function4\run.ps1: line 51
PipelineIterationInfo :

Sample code
```
# Input bindings are passed in via param block.
param($Timer)

$ErrorActionPreference = "Stop" 

# The 'IsPastDue' porperty is 'true' when the current function invocation is later than scheduled.
if ($Timer.IsPastDue) {
    Write-Host "PowerShell timer is running late!"
}
# Write an information log with the current time.
Write-Host "Function starting! TIME: $((Get-Date).ToLocalTime())"
      
try {
    $Global:SecuredPassword = (Get-AzKeyVaultsecret -VaultName $ENV:ADMIN_USER_KV -Name 
    $ENV:ADMIN_USER_SECRET).SecretValue
    $Global:Credential = [System.management.automation.pscredential]::new($Admin, $SecuredPassword)  
    
     $Scripts = ""
     $Arguments = ""
    $elements = Invoke-Command -ComputerName $computerName `
                        -Credential $Credential `
                        -Port $Port `
                        -UseSSL `
                        -SessionOption (New-PSSessionOption -SkipCACheck) `
                        -ScriptBlock $Scripts `
                        -ArgumentList $Arguments `
                        -ErrorAction Stop

    
    If ($null -ne $elements ) {        
        Foreach ($ele in $elements ) {   
            # Do something to the $rel
            $Scripts = ""
            $Arguments = ""
            $results2 = Invoke-Command -ComputerName $computerName `
                        -Credential $Credential `
                        -Port $Port `
                        -UseSSL `
                        -SessionOption (New-PSSessionOption -SkipCACheck) `
                        -ScriptBlock $Scripts `
                        -ArgumentList $Arguments `
                        -ErrorAction Stop
        }
    }
}
catch {
    Write-Error $Error[0].Exception.ToString()
}
```

**Comment by v-bafa** [comment]
Looks like the connections are from Invoke-Command, which somehow are not closed after each invocation.

Replaced with PSSession, with creating PSSession before Invoke-Command and Remove-PSSession after, then the connections stop raising.
Is there any reason we have to explicitly remove the connections? Thank you!

![image](https://github.com/Azure/azure-functions-powershell-worker/assets/28908609/ef0aa4a1-2d66-464b-827f-6cd9ba4f0db5)

**Comment by Francisco-Gamino** [comment]
Hello @v-bafa -- Could you please open a support ticket at https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request so we can take a closer look? We will follow up there. Thank you.
